set interval gif, deleted playwright, nodejs

diff --git a/.github/workflows/d2.yaml b/.github/workflows/d2.yaml
--- a/.github/workflows/d2.yaml
+++ b/.github/workflows/d2.yaml
@@ -17,16 +17,10 @@ jobs:
     steps:
     - uses: actions/checkout@v4
 
-    - name: Set up Node.js
-      uses: actions/setup-node@v4
-
     - name: Install D2
       run: |
         curl -fsSL https://d2lang.com/install.sh | sh -s --
         echo "$HOME/.local/bin" >> $GITHUB_PATH
-    
-    - name: Install Playwright
-      run: npx playwright install --with-deps
 
     - name: Export D2 files
       run: |
@@ -35,7 +29,7 @@ jobs:
           filename="${file%.*}"
           d2 "$file" "${filename}.svg" || echo "Failed to create SVG for $file"
           d2 "$file" "${filename}.png" || echo "Failed to create PNG for $file"
-          d2 "$file" "${filename}.gif" || echo "Failed to create GIF for $file"
+          d2 -animate-interval 500 "$file" "${filename}.gif" || echo "Failed to create GIF for $file"
         done
 
     - name: Check for changes
